---
dependency:
  name: galaxy
driver:
  name: docker

lint:
  name: yamllint

platforms:

  - name: photon
    groups:
      - vcsa
    image: "photon:latest"
    privileged: true
    command: /usr/lib/systemd/systemd
    volumes:
      - /Users/tscanlan/Downloads/vic-v1.1.0-bf760ea2.ova:/mnt/vic.ova:ro
  - name: centos-7
    groups:
      - vcsa
    image: centos:7
    privileged: true
    command: /usr/lib/systemd/systemd
    volumes:
      - /Users/tscanlan/Downloads/vic-v1.1.0-bf760ea2.ova:/mnt/vic.ova:ro
  - name: ubuntu-xenial
    groups:
      - vcsa
    image: ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /Users/tscanlan/Downloads/vic-v1.1.0-bf760ea2.ova:/mnt/vic.ova:ro
  - name: ubuntu-precise
    groups:
      - vcsa
    image: ubuntu:12.04
    command: /sbin/init
    privileged: true
    volumes:
      - /Users/tscanlan/Downloads/vic-v1.1.0-bf760ea2.ova:/mnt/vic.ova:ro

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../inventory/group_vars/
      host_vars: ../../inventory/host_vars/
  lint:
    name: ansible-lint
scenario:
  name: install-1.1.0
  test_sequence:
    - create
    - dependency
    - converge
    - lint
    - verify

verifier:
  name: testinfra
  enabled: false
  lint:
    name: flake8
